version: '3.0'

services : 
    clean :
        image : ejvtk:latest
        volumes:
            - ./:/work
        working_dir: /work/build
        command : make clean

    cmake:
        image : ejvtk:latest
        build : .
        volumes:
            - ./:/work
        working_dir: /work/build
        command : cmake .. -DVTK_DIR=/VTK-install/lib/cmake/vtk-9.2

    make :
        image : ejvtk:latest
        volumes:
            - ./:/work
        working_dir: /work/build
        command : make
        links:
            - cmake:cmake
