version: '3.0'

services : 
    cmake:
        image : ejvtk
        build : .
        volumes:
            - ./:/work
        working_dir: /work/build
        command : cmake .. -DVTK_DIR:PATH=/VTK-build

    make :
        image : ejvtk
        volumes:
            - ./:/work
        working_dir: /work/build
        command : make
        links:
            - cmake:cmake

    clean :
        image : ejvtk
        volumes:
            - ./:/work
        working_dir: /work/build
        command : make clean